version: "3.7"

services:
  api:
    image: node:10-alpine
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    ports:
      - "5000:5000"